#!/bin/sh
#
# $FreeBSD: net/httpry/files/httpry.in 300897 2012-07-14 14:29:18Z beat $
#
# PROVIDE: httpry
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable httpry:
#
# httpry_em0_enable (bool):		Set it to "YES" to enable httpry
#				Default is "NO".
# httpry_em0_flags (flags):		Set extra flags to httpry
#				Default is "-d -q -o /var/log/httpry.log".
#				See httpry(1) for more information.
#

. /etc/rc.subr

name=httpry_em0
rcvar=httpry_em0_enable

load_rc_config $name

: ${httpry_em0_enable="YES"}
: ${httpry_em0_flags="-i em0 -f timestamp,source-ip,source-mac,dest-ip,method,host,request-uri,user-agent -d -q -o /var/log/httpry.em0.log tcp dst port 80"}

command=/usr/local/bin/httpry_em0

run_rc_command "$1"